

= rhpam-cdc-service

Retrieves messages from KAFKA Topic (defined in search for @Incoming)

1. RHPAM TaskVariableImpl

** Schema

	{
	  "schema": {
	    "type": "struct",
	    "fields": [
	      {
		"type": "struct",
		"fields": [
		  {
		    "type": "int64",
		    "optional": false,
		    "field": "id"
		  },
		  {
		    "type": "int64",
		    "optional": true,
		    "name": "io.debezium.time.Timestamp",
		    "version": 1,
		    "field": "modificationDate"
		  },
		  {
		    "type": "string",
		    "optional": true,
		    "field": "name"
		  },
		  {
		    "type": "string",
		    "optional": true,
		    "field": "processId"
		  },
		  {
		    "type": "int64",
		    "optional": true,
		    "field": "processInstanceId"
		  },
		  {
		    "type": "int64",
		    "optional": true,
		    "field": "taskId"
		  },
		  {
		    "type": "int32",
		    "optional": true,
		    "field": "type"
		  },
		  {
		    "type": "string",
		    "optional": true,
		    "field": "value"
		  }
		],
		"optional": true,
		"name": "rhpam6.inventory.TaskVariableImpl.Value",
		"field": "before"
	      },
	      {
		"type": "struct",
		"fields": [
		  {
		    "type": "int64",
		    "optional": false,
		    "field": "id"
		  },
		  {
		    "type": "int64",
		    "optional": true,
		    "name": "io.debezium.time.Timestamp",
		    "version": 1,
		    "field": "modificationDate"
		  },
		  {
		    "type": "string",
		    "optional": true,
		    "field": "name"
		  },
		  {
		    "type": "string",
		    "optional": true,
		    "field": "processId"
		  },
		  {
		    "type": "int64",
		    "optional": true,
		    "field": "processInstanceId"
		  },
		  {
		    "type": "int64",
		    "optional": true,
		    "field": "taskId"
		  },
		  {
		    "type": "int32",
		    "optional": true,
		    "field": "type"
		  },
		  {
		    "type": "string",
		    "optional": true,
		    "field": "value"
		  }
		],
		"optional": true,
		"name": "rhpam6.inventory.TaskVariableImpl.Value",
		"field": "after"
	      },
	      {
		"type": "struct",
		"fields": [
		  {
		    "type": "string",
		    "optional": false,
		    "field": "version"
		  },
		  {
		    "type": "string",
		    "optional": false,
		    "field": "connector"
		  },
		  {
		    "type": "string",
		    "optional": false,
		    "field": "name"
		  },
		  {
		    "type": "int64",
		    "optional": false,
		    "field": "ts_ms"
		  },
		  {
		    "type": "string",
		    "optional": true,
		    "name": "io.debezium.data.Enum",
		    "version": 1,
		    "parameters": {
		      "allowed": "true,last,false"
		    },
		    "default": "false",
		    "field": "snapshot"
		  },
		  {
		    "type": "string",
		    "optional": false,
		    "field": "db"
		  },
		  {
		    "type": "string",
		    "optional": true,
		    "field": "table"
		  },
		  {
		    "type": "int64",
		    "optional": false,
		    "field": "server_id"
		  },
		  {
		    "type": "string",
		    "optional": true,
		    "field": "gtid"
		  },
		  {
		    "type": "string",
		    "optional": false,
		    "field": "file"
		  },
		  {
		    "type": "int64",
		    "optional": false,
		    "field": "pos"
		  },
		  {
		    "type": "int32",
		    "optional": false,
		    "field": "row"
		  },
		  {
		    "type": "int64",
		    "optional": true,
		    "field": "thread"
		  },
		  {
		    "type": "string",
		    "optional": true,
		    "field": "query"
		  }
		],
		"optional": false,
		"name": "io.debezium.connector.mysql.Source",
		"field": "source"
	      },
	      {
		"type": "string",
		"optional": false,
		"field": "op"
	      },
	      {
		"type": "int64",
		"optional": true,
		"field": "ts_ms"
	      },
	      {
		"type": "struct",
		"fields": [
		  {
		    "type": "string",
		    "optional": false,
		    "field": "id"
		  },
		  {
		    "type": "int64",
		    "optional": false,
		    "field": "total_order"
		  },
		  {
		    "type": "int64",
		    "optional": false,
		    "field": "data_collection_order"
		  }
		],
		"optional": true,
		"field": "transaction"
	      }
	    ],
	    "optional": false,
	    "name": "rhpam6.inventory.TaskVariableImpl.Envelope"
	  },
	  "payload": {
	    "before": null,
	    "after": {
	      "id": 2,
	      "modificationDate": 1607680532000,
	      "name": "tImportantVarIn",
	      "processId": "ht-basics.simple-ht",
	      "processInstanceId": 2,
	      "taskId": 2,
	      "type": 0,
	      "value": "Level-0"
	    },
	    "source": {
	      "version": "1.3.1.Final",
	      "connector": "mysql",
	      "name": "rhpam6",
	      "ts_ms": 1607680532000,
	      "snapshot": "false",
	      "db": "inventory",
	      "table": "TaskVariableImpl",
	      "server_id": 223344,
	      "gtid": null,
	      "file": "mysql-bin.000003",
	      "pos": 123187,
	      "row": 0,
	      "thread": null,
	      "query": null
	    },
	    "op": "c",
	    "ts_ms": 1607680532198,
	    "transaction": null
	  }
	}

** Places the content in DB Structure


	taskdetails=> select * from taskvariables;
	 id |     changedate      |      name       | proceinstanceid | taskid |  value  
	----+---------------------+-----------------+-----------------+--------+---------
	  1 | 2021-01-06 14:13:31 | tImportantVarIn |               2 |      2 | level-2
	  2 | 2021-01-06 14:14:45 | tImportantVarIn |               3 |      3 | level-3








